// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(RoomMateDBContext))]
    [Migration("20240506153827_AddMigrationToResolveWorkShift")]
    partial class AddMigrationToResolveWorkShift
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DAL.Entities.HouseWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HouseWork");
                });

            modelBuilder.Entity("DAL.Entities.Roomate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomMate");
                });

            modelBuilder.Entity("DAL.Entities.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseWorkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomateId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseWorkId");

                    b.HasIndex("RoomateId");

                    b.ToTable("WorkShift");
                });

            modelBuilder.Entity("DAL.Entities.WorkShift", b =>
                {
                    b.HasOne("DAL.Entities.HouseWork", "HouseWork")
                        .WithMany()
                        .HasForeignKey("HouseWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Roomate", "Roomate")
                        .WithMany()
                        .HasForeignKey("RoomateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseWork");

                    b.Navigation("Roomate");
                });
#pragma warning restore 612, 618
        }
    }
}
